export const change_input_value = 'change_input_value'
export const add_todo_item = 'add_todo_item'
export const delete_todo_item = 'delete_todo_item'
export const init_list = 'init_list'
export const fetch_init_list = 'fetch_init_list'